# Build and Release pipeline for VTS
# Changes may need to be made
name: Release pipeline

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: nano

jobs:
  envs:
    runs-on: ubuntu-latest
    steps:
      - id: envs
        name: Get repo name as ENV var
        run: |
          echo "repo_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "author=$(curl -sSL ${{ github.event.repository.owner.url }} | jq -r '.name')" >> $GITHUB_OUTPUT

    outputs:
      repo_name: ${{ steps.envs.outputs.repo_name }}
      author: ${{ steps.envs.outputs.author }}

  maven-build:
    runs-on: ubuntu-latest
    needs: envs
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Maven Build
        run: ./mvnw test package

      - name: Upload Warfile
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.envs.outputs.repo_name }}.war
          path: target/${{ needs.envs.outputs.repo_name }}.war
          retention-days: 5

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [envs, maven-build]

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download warfile
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.envs.outputs.repo_name }}.war
          path: ./target

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/${{ needs.envs.outputs.repo_name }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.authors=${{ needs.envs.outputs.repo_name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
